name: Automation rest
on: push
jobs:
  my-jobs: print hellow india
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v4
      - name: Install python
        run: sudo apt-get install python3
      - name: Install selenium
        run: pip install selenium
      - name: pip install Chrome Driver
        run: pip install chromedriver-autoinstaller
      - name: chromedriver install
        run: chmod +x drivers/chromedriver.exe
      - name: Run Test file
        run: python sample1.yml
